######################################################################
# Automatically generated by qmake (3.0) lun. nov. 30 11:21:53 2015
######################################################################

TEMPLATE = app
TARGET = testVipInterpreter
INCLUDEPATH += . ../../src
QMAKE_CXXFLAGS += -std=c++14
OBJECTS_DIR = bin
QT += testlib

# Input
HEADERS += \ 
    testvipinterpreter.hpp \
    ../../src/vnet/vipinterpreter.h
SOURCES += \ 
    testvipinterpreter.cpp
OBJECTS += \
    ../../bin/vipinterpreter.o \
    ../../bin/vipheader.o \
    ../../bin/netstream.o
