######################################################################
# Automatically generated by qmake (3.0) lun. nov. 30 11:21:53 2015
######################################################################

TEMPLATE = app
TARGET = testVipInterpreter
INCLUDEPATH += . ../../src ../../src/net ..
QMAKE_CXXFLAGS += -std=c++14
OBJECTS_DIR = bin
QT += testlib

# Input
HEADERS += \
    testnetinterpreter.hpp \
    ../../src/net/netinterpreter.hpp
SOURCES += \
    testnetinterpreter.cpp
OBJECTS += \
	../../bin/netstream.o \
	../../bin/varpheader.o \
	../../bin/netinterpreter.o
