######################################################################
# Automatically generated by qmake (3.0) lun. nov. 30 11:21:53 2015
######################################################################

TEMPLATE = app
TARGET = testnetstream
INCLUDEPATH += . ../../src
CONFIG += c++11
QT += testlib

# Input
HEADERS += testnetstream.hpp ../../src/net/netstream.hpp
SOURCES += testnetstream.cpp
OBJECTS += ../../bin/netstream.o
