######################################################################
# Automatically generated by qmake (3.0) lun. nov. 30 11:21:53 2015
######################################################################

TEMPLATE = app
TARGET = testnetstream
INCLUDEPATH += . ../../src .. ../../src/net
QMAKE_CXXFLAGS += -std=c++14
OBJECTS_DIR = bin
QT += testlib

# Input
HEADERS += testnetstream.hpp \
    ../fakedevice.hpp
SOURCES += testnetstream.cpp
OBJECTS += ../../bin/netstream.o
