######################################################################
# Automatically generated by qmake (3.0) lun. nov. 30 11:21:53 2015
######################################################################

TEMPLATE = app
TARGET = testSdcpInterpreter
INCLUDEPATH += . ../../src ../../src/vnet .. ../../src/net
QMAKE_CXXFLAGS += -std=c++14
OBJECTS_DIR = bin
QT += testlib

# Input
HEADERS += \ 
    testsdcpinterpreter.hpp
SOURCES += \
    testsdcpinterpreter.cpp
OBJECTS += \
    ../../bin/device.o \
    ../../bin/vipinterpreter.o \
    ../../bin/sdcpinterpreter.o \
    ../../bin/vipheader.o \
    ../../bin/netstream.o
