######################################################################
# Automatically generated by qmake (3.0) dim. déc. 6 15:22:56 2015
######################################################################

TEMPLATE = app
TARGET = testDynamicBitset
INCLUDEPATH += .

# Input
HEADERS += testdynamicbitset.hpp
SOURCES += testdynamicbitset.cpp
