######################################################################
# Automatically generated by qmake (3.0) dim. déc. 6 15:26:03 2015
######################################################################

TEMPLATE = app
TARGET = testDynamicBitset
INCLUDEPATH += . ../../src
CONFIG += c++11
QT += testlib

# Input
HEADERS += testdynamicbitset.hpp ../../src/dynamicbitset.hpp
SOURCES += testdynamicbitset.cpp
