######################################################################
# Automatically generated by qmake (3.0) dim. d�c. 6 15:26:03 2015
######################################################################

TEMPLATE = app
TARGET = testDynamicBitset
INCLUDEPATH += . ../../src
QMAKE_CXXFLAGS += -std=c++14
OBJECTS_DIR = bin
QT += testlib

# Input
HEADERS += testdynamicbitset.hpp ../../src/dynamicbitset.hpp
SOURCES += testdynamicbitset.cpp
