######################################################################
# Automatically generated by qmake (3.0) jeu. nov. 26 13:28:11 2015
######################################################################

QT += testlib
CONFIG += c++11
TEMPLATE = app
TARGET = test
INCLUDEPATH += .

# Input
HEADERS += netstream.hpp testnetstream.hpp
SOURCES += testnetstream.cpp
